name: Build and Test Demo

on:
    push:
        branches: [main]

jobs:
    test-app:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm ci
            - run: npm run test

    build-app:
        runs-on: ubuntu-latest
        needs: test-app
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm ci
            - run: npm run build
